In [1]:
import numpy as np

In [2]:
import torchscsp

In [3]:
from importlib import reload

In [4]:
reload(torchscsp)

<module 'torchscsp' from '/Users/tony/Work/GitHub.com-mirror/pyscsp/torchscsp.py'>

In [5]:
torchscsp.dxmask()

tensor([[ 0.0000,  0.0000,  0.0000],
        [-0.5000,  0.0000,  0.5000],
        [ 0.0000,  0.0000,  0.0000]], dtype=torch.float64)

In [6]:
torchscsp.make1Dsamplgaussfilter(1)

tensor([0.0044, 0.0540, 0.2420, 0.3989, 0.2420, 0.0540, 0.0044])

In [7]:
torchscsp.jet2mask(Cx=1.0)

tensor([[ 0.0000,  0.0000,  0.0000],
        [-0.5000,  0.0000,  0.5000],
        [ 0.0000,  0.0000,  0.0000]], dtype=torch.float64)

In [8]:
torchscsp.jet2mask(Cy=1.0)

tensor([[ 0.0000,  0.5000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000, -0.5000,  0.0000]], dtype=torch.float64)

In [9]:
torchscsp.jet2mask(Cxx=1.0)

tensor([[ 0.0000,  0.0000,  0.0000],
        [ 0.5000, -1.0000,  0.5000],
        [ 0.0000,  0.0000,  0.0000]], dtype=torch.float64)

In [10]:
torchscsp.jet2mask(Cxy=1.0)

tensor([[-0.1250,  0.0000,  0.1250],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.1250,  0.0000, -0.1250]], dtype=torch.float64)

In [11]:
torchscsp.jet2mask(Cyy=1.0)

tensor([[ 0.0000,  0.5000,  0.0000],
        [ 0.0000, -1.0000,  0.0000],
        [ 0.0000,  0.5000,  0.0000]], dtype=torch.float64)

In [12]:
torchscsp.make1Dsamplgaussfilter(1)

tensor([0.0044, 0.0540, 0.2420, 0.3989, 0.2420, 0.0540, 0.0044])

In [13]:
torchscsp.make1Dintgaussfilter(1)

tensor([0.0060, 0.0606, 0.2417, 0.3829, 0.2417, 0.0606, 0.0060])

In [14]:
torchscsp.make1Dlinintgaussfilter(1)

tensor([0.0077, 0.0667, 0.2408, 0.3687, 0.2408, 0.0667, 0.0077])

In [15]:
torchscsp.make1Dgaussfilter(1)

tensor([0.0044, 0.0540, 0.2420, 0.3989, 0.2420, 0.0540, 0.0044])

In [16]:
type(torchscsp.make1Dgaussfilter(1))

torch.Tensor