In [1]:
import numpy as np
import torch, pyscsp
import pyscsp.torchscsp as torchscsp
from importlib import reload

In [2]:
reload(pyscsp.torchscsp)

<module 'pyscsp.torchscsp' from '/Users/tony/Work/GitHub.com-mirror/pyscsp/pyscsp/torchscsp.py'>

In [3]:
torchscsp.dxmask()

tensor([[ 0.0000,  0.0000,  0.0000],
        [-0.5000,  0.0000,  0.5000],
        [ 0.0000,  0.0000,  0.0000]])

In [4]:
torchscsp.make1Dsamplgaussfilter(1)

tensor([0.0044, 0.0540, 0.2420, 0.3989, 0.2420, 0.0540, 0.0044])

In [5]:
torchscsp.jet2mask(Cx=1.0)

tensor([[ 0.0000,  0.0000,  0.0000],
        [-0.5000,  0.0000,  0.5000],
        [ 0.0000,  0.0000,  0.0000]])

In [6]:
torchscsp.jet2mask(Cy=1.0)

tensor([[ 0.0000,  0.5000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000, -0.5000,  0.0000]])

In [7]:
torchscsp.jet2mask(Cxx=1.0)

tensor([[ 0.0000,  0.0000,  0.0000],
        [ 0.5000, -1.0000,  0.5000],
        [ 0.0000,  0.0000,  0.0000]])

In [8]:
torchscsp.jet2mask(Cxy=1.0)

tensor([[-0.1250,  0.0000,  0.1250],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.1250,  0.0000, -0.1250]])

In [9]:
torchscsp.jet2mask(Cyy=1.0)

tensor([[ 0.0000,  0.5000,  0.0000],
        [ 0.0000, -1.0000,  0.0000],
        [ 0.0000,  0.5000,  0.0000]])

In [10]:
torchscsp.make1Dsamplgaussfilter(1)

tensor([0.0044, 0.0540, 0.2420, 0.3989, 0.2420, 0.0540, 0.0044])

In [11]:
torchscsp.make1Dnormsamplgaussfilter(1)

tensor([0.0044, 0.0540, 0.2420, 0.3991, 0.2420, 0.0540, 0.0044])

In [12]:
torchscsp.make1Dintgaussfilter(1)

tensor([0.0060, 0.0606, 0.2417, 0.3829, 0.2417, 0.0606, 0.0060])

In [13]:
torchscsp.make1Dlinintgaussfilter(1)

tensor([0.0077, 0.0667, 0.2408, 0.3687, 0.2408, 0.0667, 0.0077])

In [14]:
torchscsp.make1Dgaussfilter(1)

tensor([0.0082, 0.0499, 0.2079, 0.4658, 0.2079, 0.0499, 0.0082])

In [15]:
torchscsp.make1Dsamplgaussfilter(0.7)

tensor([0.0096, 0.2054, 0.5699, 0.2054, 0.0096])

In [16]:
torchscsp.make1Dnormsamplgaussfilter(0.7)

tensor([0.0096, 0.2054, 0.5699, 0.2054, 0.0096])

In [17]:
torchscsp.make1Dintgaussfilter(0.7)

tensor([0.0159, 0.2215, 0.5249, 0.2215, 0.0159])

In [18]:
torchscsp.make1Dlinintgaussfilter(0.7)

tensor([0.0232, 0.2315, 0.4897, 0.2315, 0.0232])

In [19]:
torchscsp.make1Dgaussfilter(0.7)

tensor([0.0188, 0.1546, 0.6500, 0.1546, 0.0188])

In [20]:
torchscsp.make1Dsamplgaussfilter(0.3)

tensor([0.0051, 1.3298, 0.0051])

In [21]:
torchscsp.make1Dnormsamplgaussfilter(0.3)

tensor([0.0038, 0.9923, 0.0038])

In [22]:
torchscsp.make1Dintgaussfilter(0.3)

tensor([0.0478, 0.9044, 0.0478])

In [23]:
torchscsp.make1Dlinintgaussfilter(0.3)

tensor([0.1196, 0.7607, 0.1196])

In [24]:
torchscsp.make1Dgaussfilter(0.3)

tensor([0.0412, 0.9158, 0.0412])

In [25]:
torchscsp.filtersdev(torchscsp.make1Dsamplgaussfilter(0.7))

0.6984325156494019

In [26]:
torchscsp.filtersdev(torchscsp.make1Dnormsamplgaussfilter(0.7))

0.6984324162786772

In [27]:
torchscsp.filtersdev(torchscsp.make1Dintgaussfilter(0.7))

0.7551201312618119

In [28]:
torchscsp.filtersdev(torchscsp.make1Dlinintgaussfilter(0.7))

0.8058098382168808

In [29]:
torchscsp.filtersdev(torchscsp.make1Dgaussfilter(0.7))

0.6788509537008834

In [30]:
torchscsp.filtersdev(torchscsp.make1Dsamplgaussfilter(0.3))

0.08759265880707422

In [31]:
torchscsp.filtersdev(torchscsp.make1Dnormsamplgaussfilter(0.3))

0.08759274336051885

In [32]:
torchscsp.filtersdev(torchscsp.make1Dintgaussfilter(0.3))

0.30916040817575147

In [33]:
torchscsp.filtersdev(torchscsp.make1Dlinintgaussfilter(0.3))

0.4891287268116519

In [34]:
torchscsp.filtersdev(torchscsp.make1Dgaussfilter(0.3))

0.2872146070984246