In [12]:
import math
import numpy as np
import torch, torchscsp, affscsp
from importlib import reload

In [13]:
reload(torchscsp)

<module 'torchscsp' from '/Users/tony/Work/python/pyscsp/torchscsp.py'>

In [3]:
from importlib import reload

In [26]:
torchscsp.makesamplaffgausskernel(8, 4, math.pi/6, 32)

tensor([[1.9872e-29, 9.0033e-29, 3.9690e-28,  ..., 3.3391e-11, 2.7766e-11,
         2.2466e-11],
        [1.8838e-28, 8.3632e-28, 3.6127e-27,  ..., 8.9925e-11, 7.3275e-11,
         5.8097e-11],
        [1.6973e-27, 7.3839e-27, 3.1256e-26,  ..., 2.3018e-10, 1.8380e-10,
         1.4280e-10],
        ...,
        [1.4280e-10, 1.8380e-10, 2.3018e-10,  ..., 3.1256e-26, 7.3839e-27,
         1.6973e-27],
        [5.8097e-11, 7.3275e-11, 8.9925e-11,  ..., 3.6127e-27, 8.3632e-28,
         1.8838e-28],
        [2.2466e-11, 2.7766e-11, 3.3391e-11,  ..., 3.9690e-28, 9.0033e-29,
         1.9872e-29]], dtype=torch.float64)

In [22]:
torchscsp.makescnormdirdermask(8, 4, math.pi/6, 1, 0)

tensor([[ 0.0000,  2.0000,  0.0000],
        [-3.4641,  0.0000,  3.4641],
        [ 0.0000, -2.0000,  0.0000]], dtype=torch.float64)

In [20]:
torchscsp.makeL1normdirdermask(8, 4, math.pi/6, 1, 0)

tensor([[ 0.0000,  2.5066,  0.0000],
        [-4.3416,  0.0000,  4.3416],
        [ 0.0000, -2.5066,  0.0000]], dtype=torch.float64)

In [23]:
torchscsp.makescnormdirdermask(8, 4, math.pi/6, 2, 0)

tensor([[ -13.8564,   16.0000,   13.8564],
        [  48.0000, -128.0000,   48.0000],
        [  13.8564,   16.0000,  -13.8564]], dtype=torch.float64)

In [24]:
torchscsp.makeL1normdirdermask(8, 4, math.pi/6, 2, 0)

tensor([[ -14.3162,   16.5309,   14.3162],
        [  49.5928, -132.2474,   49.5928],
        [  14.3162,   16.5309,  -14.3162]], dtype=torch.float64)

In [27]:
gauss84_30 = torchscsp.makesamplaffgausskernel(8, 4, math.pi/6, 32)

In [28]:
scnormmask_phi = torchscsp.makescnormdirdermask(8, 4, math.pi/6, 1, 0)

In [29]:
L1normmask_phi = torchscsp.makeL1normdirdermask(8, 4, math.pi/6, 1, 0)